# Tweet the URL of a commit on @sklearn_commits whenever a push event
# happens on the master branch
name: Twitter Push Notification


on:
  branches:
    - master
    - twitter-test-branch


jobs:
  tweet:
    name: Twitter Notification
    runs-on: ubuntu-latest
    steps:
      - name: Tweet Push on the https://twitter.com/sklearn_commits account
        uses: xorilog/twitter-action@0.2
        with:
          args: "-message \"${{ github.event.html_url}}/commit/${{ github.event.head }}\""
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
